language: java
jdk:
    - openjdk8
    - oraclejdk8
install:
    - git clone https://github.com/clarus-proxy/dataoperations-api.git && cd dataoperations-api && git checkout develop && mvn install && cd ..
